# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{g_form_submit_protector}
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C. Jason Harrelson (midas)"]
  s.date = %q{2010-06-08}
  s.description = %q{A Rails Guilded component that will disable form elements once the submit button has been used.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "g_form_submit_protector.gemspec",
     "lib/g_form_submit_protector.rb",
     "lib/g_form_submit_protector/view_helpers.rb",
     "lib/generators/form_submit_protector_assets/form_submit_protector_assets_generator.rb",
     "lib/generators/form_submit_protector_assets/templates/guilded.form_submit_protector.js",
     "lib/generators/form_submit_protector_assets/templates/guilded.form_submit_protector.min.js",
     "lib/generators/form_submit_protector_assets/templates/jquery-disable_on_submit-1.0.js",
     "lib/generators/form_submit_protector_assets/templates/jquery-disable_on_submit-1.0.min.js",
     "rails_generators/form_submit_protector_assets/form_submit_protector_assets_generator.rb",
     "rails_generators/form_submit_protector_assets/templates/guilded.form_submit_protector.js",
     "rails_generators/form_submit_protector_assets/templates/guilded.form_submit_protector.min.js",
     "rails_generators/form_submit_protector_assets/templates/jquery-disable_on_submit-1.0.js",
     "rails_generators/form_submit_protector_assets/templates/jquery-disable_on_submit-1.0.min.js",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/g_form_submit_protector_spec.rb",
     "spec/generators/form_submit_protector_assets_generator_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/midas/g_form_submit_protector}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Rails Guilded component that will disable form elements once the submit button has been used.}
  s.test_files = [
    "spec/g_form_submit_protector_spec.rb",
     "spec/generators/form_submit_protector_assets_generator_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 2.3"])
      s.add_runtime_dependency(%q<guilded>, [">= 1.0"])
    else
      s.add_dependency(%q<rails>, [">= 2.3"])
      s.add_dependency(%q<guilded>, [">= 1.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 2.3"])
    s.add_dependency(%q<guilded>, [">= 1.0"])
  end
end

